export const Fonts = Object.freeze({
  // Black: 'EuclidSquare-Black',
  // BlackItalic: 'EuclidSquare-BlackItalic',
  AvigeaItalic:'Avigea-Italic',
  Avigea:'Avigea',
  AvigeaRegular:'Avigea-Regular',
  Bold: 'EuclidSquare-Bold',
  BoldItalic: 'OSerif-Italic',
  // ExtraBold: 'EuclidSquare-ExtraBold',
  // ExtraBoldItalic: 'EuclidSquare-ExtraBoldItalic',
  // Heavy: 'EuclidSquare-Heavy',
  // HeavyItalic: 'EuclidSquare-HeavyItalic',
  Light: 'EuclidSquare-Light',
  LightItalic: 'EuclidSquare-Light Italic',
  Medium: 'EuclidSquare-Medium',
  MediumItalic: 'EuclidSquare-MediumItalic',
  Regular: 'OSerif-Regular',
  RegularItalic: 'EuclidSquare-RegularItalic',
  SemiBold: 'EuclidSquare-SemiBold',
  SemiBoldItalic: 'EuclidSquare-SemiBoldItalic',
  // Thin: 'EuclidSquare-Thin',
  // ThinItalic: 'EuclidSquare-ThinItalic',
  // UltraLight: 'EuclidSquare-UltraLight',
  // UltraLightItalic: 'EuclidSquare-UltraLightItalic',
});
