export const Icons = Object.freeze({
    ic_phone: require('../../assets/icons/ic_outline_phone.png'),
  icOpenEye: require('../../assets/icons/ic_open_eye.png'),
  ic_mega_email: require('../../assets/icons/mage_email_fill.png'),
  ic_user: require('../../assets/icons/tabler_user.png'),
  ic_uncheck: require('../../assets/icons/ic_uncheck.png'),
  ic_home: require('../../assets/icons/ic_home.png'),
  ic_explore: require('../../assets/icons/ic_explore.png'),
  ic_progress: require('../../assets/icons/ic_progress.png'),
  icon_book: require('../../assets/icons/icon_book.png'),
  backButton: require('../../assets/images/download.png'),
  ic_pen: require('../../assets/images/download.png'),
  ic_camera: require('../../assets/images/download.png'),
  // icAccount: require('../../assets/icons/icAcount.png'),
  // icAccountFill: require('../../assets/icons/icAccountFill.png'),
  // icCalender: require('../../assets/icons/icCalender.png'),
  // icLocationPin: require('../../assets/icons/locationPin.png'),
   icMagnifier: require('../../assets/icons/icMagnifier.png'),
  // icPassword: require('../../assets/icons/icPassword.png'),
  // arrowRight: require('../../assets/icons/arrowRight.png'),
  // icImagePicker: require('../../assets/icons/icImagePicker.png'),
  // icDownload: require('../../assets/icons/icDownload.png'),
  // icTaskAssigneUser: require('../../assets/icons/icTaskAssigneUser.png'),
  // icLogout: require('../../assets/icons/icLogout.png'),
  // icBackButton: require('../../assets/icons/icBackButton.png'),
  // icClock: require('../../assets/icons/icClock.png'),
  // icPrivacyPolicy: require('../../assets/icons/icPrivacyPolicy.png'),
  // icTermCondition: require('../../assets/icons/icTermCondition.png'),
  // icSend: require('../../assets/icons/icSend.png'),
  // icAttachFile: require('../../assets/icons/icAttachFile.png'),
  // icFilter: require('../../assets/icons/icFilter.png'),
  // icFilterMenu: require('../../assets/icons/icFilterMenu.png'),
  // icRadioChecked: require('../../assets/icons/icRadioButtonChecked.png'),
  // icRadioUnchecked: require('../../assets/icons/icRadioButtonUnchecked.png'),
  // icClose: require('../../assets/icons/icClose.png'),
});
