export const Images = Object.freeze({
  LoginLogo: require('../../assets/images/download.png'),
  // icAccount: require('../../assets/icons/icAcount.png'),
  backgroundScreen: require('../../assets/images/download.png'),
  StartScreen1: require('../../assets/images/download.png'),
  StartScreen2: require('../../assets/images/download.png'),
  StartScreen3: require('../../assets/images/download.png'),
  social_google: require('../../assets/images/download.png'),
  social_apple: require('../../assets/images/download.png'),
  social_facebook: require('../../assets/images/download.png'),
  Otp_image: require('../../assets/images/download.png'),
  icUser: require('../../assets/images/download.png'),
  icNotification: require('../../assets/images/download.png'),
  ic_excercise: require('../../assets/images/download.png'),
  frame_card: require('../../assets/images/download.png'),
  frame_card2: require('../../assets/images/download.png'),
  ic_sleep: require('../../assets/images/download.png'),
  ic_exercise2: require('../../assets/images/download.png'),
  ic_hotcold: require('../../assets/images/download.png'),
  ic_nutrition: require('../../assets/images/download.png'),
  ic_consultant: require('../../assets/images/download.png'),
  ic_supplement: require('../../assets/images/download.png'),
  icons_clock: require('../../assets/images/download.png'),
  book_frame: require('../../assets/images/download.png'),
  progress_sreach: require('../../assets/images/download.png'),
  meditation_book: require('../../assets/images/download.png'),
  forwardIcon: require('../../assets/images/download.png'),
  videoBackgroundImage: require('../../assets/images/download.png'),
  Signout: require('../../assets/images/download.png'),
  backButton: require('../../assets/images/download.png'),
  flag_english: require('../../assets/images/download.png'),
  flag_france: require('../../assets/images/download.png'),
  flag_spain: require('../../assets/images/download.png'),
  flag_german: require('../../assets/images/download.png'),
  radio_button: require('../../assets/images/download.png'),
  radio_button_check: require('../../assets/images/download.png'),
  ic_exercise3: require('../../assets/images/download.png'),
  ic_play: require('../../assets/images/download.png'),
  round_check: require('../../assets/images/download.png'),
  icon_down: require('../../assets/images/download.png'),
  image_save: require('../../assets/images/download.png'),
  icMapImage: require('../../assets/images/download.png'),
  assigneMember: require('../../assets/images/download.png'),
  assigneMember2: require('../../assets/images/download.png'),
  
});
