export const Images = Object.freeze({
  // icAccount: require('../../assets/icons/icAcount.png'),
 LoginLogo: require('../../assets/images/LoginLogo.png'),
  backgroundScreen: require('../../assets/images/backgroundScreen.png'),
  StartScreen1: require('../../assets/images/StartScreen1.png'),
  StartScreen2: require('../../assets/images/StartScreen2.png'),
  StartScreen3: require('../../assets/images/StartScreen3.png'),
  social_google: require('../../assets/images/social_google.png'),
  social_apple: require('../../assets/images/social_apple.png'),
  social_facebook: require('../../assets/images/social_faebook.png'),
  Otp_image: require('../../assets/images/Otp_image.png'),
  icUser: require('../../assets/images/user_Ellipse.png'),
  icNotification: require('../../assets/images/Noti_Image.png'),
  ic_excercise: require('../../assets/images/ic_excercise.png'),
  frame_card: require('../../assets/images/frame_card.png'),
  frame_card2: require('../../assets/images/fram_card2.png'),
  ic_sleep: require('../../assets/images/ic_sleep.png'),
  ic_exercise2: require('../../assets/images/ic_exercise2.png'),
  ic_hotcold: require('../../assets/images/ic_hotcold.png'),
  ic_nutrition: require('../../assets/images/ic_nutrition.png'),
  ic_consultant: require('../../assets/images/ic_consultant.png'),
  ic_supplement: require('../../assets/images/ic_supplement.png'),
  icons_clock: require('../../assets/images/icons_clock.png'),
  book_frame: require('../../assets/images/book_frame.png'),
  progress_sreach: require('../../assets/images/progress_sreach.png'),
  meditation_book: require('../../assets/images/meditation_book.png'),
  forwardIcon: require('../../assets/images/download.png'),
  videoBackgroundImage: require('../../assets/images/download.png'),
  Signout: require('../../assets/images/download.png'),
  backButton: require('../../assets/images/download.png'),
  flag_english: require('../../assets/images/download.png'),
  flag_france: require('../../assets/images/download.png'),
  flag_spain: require('../../assets/images/download.png'),
  flag_german: require('../../assets/images/download.png'),
  radio_button: require('../../assets/images/download.png'),
  radio_button_check: require('../../assets/images/download.png'),
  ic_exercise3: require('../../assets/images/download.png'),
  ic_play: require('../../assets/images/download.png'),
  round_check: require('../../assets/images/download.png'),
  icon_down: require('../../assets/images/download.png'),
  image_save: require('../../assets/images/download.png'),
  icMapImage: require('../../assets/images/download.png'),
  assigneMember: require('../../assets/images/download.png'),
  assigneMember2: require('../../assets/images/download.png'),
  
});
